-- ============================================================================
-- Kredora — seed problem_tests (server-side hidden + sample test cases)
-- ============================================================================
-- GENERATED FILE — do not edit by hand. Regenerate with:
--   node scripts/generate-seed-tests.mjs
--
-- Run in Supabase Dashboard -> SQL Editor after supabase/schema.sql.
-- Idempotent: wipes and re-seeds all test rows for every known problem.
-- ============================================================================

delete from public.problem_tests
where problem_id in (
  'two-sum',
  'valid-palindrome',
  'valid-parentheses',
  'maximum-subarray',
  'container-with-most-water',
  'longest-substring-without-repeating-characters',
  'climbing-stairs',
  'trapping-rain-water',
  'binary-search',
  'coin-change',
  'valid-anagram',
  'reverse-linked-list',
  'binary-tree-inorder-traversal',
  'maximum-depth-of-binary-tree',
  'intersection-of-two-arrays',
  'fibonacci-number',
  'single-number',
  'move-zeroes',
  'plus-one',
  'contains-duplicate',
);

insert into public.problem_tests (problem_id, kind, input, expected) values
  ('two-sum', 'sample', '{"input":[[2,7,11,15],9],"inputDisplay":"nums = [2,7,11,15], target = 9"}::jsonb', '[0,1]::jsonb'),
  ('two-sum', 'sample', '{"input":[[3,2,4],6],"inputDisplay":"nums = [3,2,4], target = 6"}::jsonb', '[1,2]::jsonb'),
  ('two-sum', 'sample', '{"input":[[3,3],6],"inputDisplay":"nums = [3,3], target = 6"}::jsonb', '[0,1]::jsonb'),
  ('two-sum', 'hidden', '{"input":[[1,5,8,12,19,25],27]}::jsonb', '[2,4]::jsonb'),
  ('two-sum', 'hidden', '{"input":[[-3,4,3,90],0]}::jsonb', '[0,2]::jsonb'),
  ('two-sum', 'hidden', '{"input":[[0,4,3,0],0]}::jsonb', '[0,3]::jsonb'),
  ('two-sum', 'hidden', '{"input":[[1000000,500,-1000000],-999500]}::jsonb', '[1,2]::jsonb'),
  ('valid-palindrome', 'sample', '{"input":["A man, a plan, a canal: Panama"],"inputDisplay":"s = \"A man, a plan, a canal: Panama\""}::jsonb', 'true::jsonb'),
  ('valid-palindrome', 'sample', '{"input":["race a car"],"inputDisplay":"s = \"race a car\""}::jsonb', 'false::jsonb'),
  ('valid-palindrome', 'sample', '{"input":[" "],"inputDisplay":"s = \" \""}::jsonb', 'true::jsonb'),
  ('valid-palindrome', 'hidden', '{"input":["0P"]}::jsonb', 'false::jsonb'),
  ('valid-palindrome', 'hidden', '{"input":["ab_a"]}::jsonb', 'true::jsonb'),
  ('valid-palindrome', 'hidden', '{"input":["Was it a car or a cat I saw?"]}::jsonb', 'true::jsonb'),
  ('valid-parentheses', 'sample', '{"input":["()"],"inputDisplay":"s = \"()\""}::jsonb', 'true::jsonb'),
  ('valid-parentheses', 'sample', '{"input":["()[]{}"],"inputDisplay":"s = \"()[]{}\""}::jsonb', 'true::jsonb'),
  ('valid-parentheses', 'sample', '{"input":["(]"],"inputDisplay":"s = \"(]\""}::jsonb', 'false::jsonb'),
  ('valid-parentheses', 'sample', '{"input":["([])"],"inputDisplay":"s = \"([])\""}::jsonb', 'true::jsonb'),
  ('valid-parentheses', 'hidden', '{"input":["["]}::jsonb', 'false::jsonb'),
  ('valid-parentheses', 'hidden', '{"input":["]"]}::jsonb', 'false::jsonb'),
  ('valid-parentheses', 'hidden', '{"input":["{[]}(){[()()]}"]}::jsonb', 'true::jsonb'),
  ('valid-parentheses', 'hidden', '{"input":["(((((((((())))))))))"]}::jsonb', 'true::jsonb'),
  ('maximum-subarray', 'sample', '{"input":[[-2,1,-3,4,-1,2,1,-5,4]],"inputDisplay":"nums = [-2,1,-3,4,-1,2,1,-5,4]"}::jsonb', '6::jsonb'),
  ('maximum-subarray', 'sample', '{"input":[[1]],"inputDisplay":"nums = [1]"}::jsonb', '1::jsonb'),
  ('maximum-subarray', 'sample', '{"input":[[5,4,-1,7,8]],"inputDisplay":"nums = [5,4,-1,7,8]"}::jsonb', '23::jsonb'),
  ('maximum-subarray', 'hidden', '{"input":[[-1]]}::jsonb', '-1::jsonb'),
  ('maximum-subarray', 'hidden', '{"input":[[-5,-2,-8,-1]]}::jsonb', '-1::jsonb'),
  ('maximum-subarray', 'hidden', '{"input":[[2,-1,3,4,-5,10]]}::jsonb', '13::jsonb'),
  ('container-with-most-water', 'sample', '{"input":[[1,8,6,2,5,4,8,3,7]],"inputDisplay":"height = [1,8,6,2,5,4,8,3,7]"}::jsonb', '49::jsonb'),
  ('container-with-most-water', 'sample', '{"input":[[1,1]],"inputDisplay":"height = [1,1]"}::jsonb', '1::jsonb'),
  ('container-with-most-water', 'hidden', '{"input":[[4,3,2,1,4]]}::jsonb', '16::jsonb'),
  ('container-with-most-water', 'hidden', '{"input":[[1,2,1]]}::jsonb', '2::jsonb'),
  ('container-with-most-water', 'hidden', '{"input":[[2,3,4,5,18,17,6]]}::jsonb', '17::jsonb'),
  ('longest-substring-without-repeating-characters', 'sample', '{"input":["abcabcbb"],"inputDisplay":"s = \"abcabcbb\""}::jsonb', '3::jsonb'),
  ('longest-substring-without-repeating-characters', 'sample', '{"input":["bbbbb"],"inputDisplay":"s = \"bbbbb\""}::jsonb', '1::jsonb'),
  ('longest-substring-without-repeating-characters', 'sample', '{"input":["pwwkew"],"inputDisplay":"s = \"pwwkew\""}::jsonb', '3::jsonb'),
  ('longest-substring-without-repeating-characters', 'hidden', '{"input":[""]}::jsonb', '0::jsonb'),
  ('longest-substring-without-repeating-characters', 'hidden', '{"input":[" "]}::jsonb', '1::jsonb'),
  ('longest-substring-without-repeating-characters', 'hidden', '{"input":["au"]}::jsonb', '2::jsonb'),
  ('longest-substring-without-repeating-characters', 'hidden', '{"input":["dvdf"]}::jsonb', '3::jsonb'),
  ('climbing-stairs', 'sample', '{"input":[2],"inputDisplay":"n = 2"}::jsonb', '2::jsonb'),
  ('climbing-stairs', 'sample', '{"input":[3],"inputDisplay":"n = 3"}::jsonb', '3::jsonb'),
  ('climbing-stairs', 'sample', '{"input":[4],"inputDisplay":"n = 4"}::jsonb', '5::jsonb'),
  ('climbing-stairs', 'hidden', '{"input":[1]}::jsonb', '1::jsonb'),
  ('climbing-stairs', 'hidden', '{"input":[5]}::jsonb', '8::jsonb'),
  ('climbing-stairs', 'hidden', '{"input":[8]}::jsonb', '34::jsonb'),
  ('trapping-rain-water', 'sample', '{"input":[[0,1,0,2,1,0,1,3,2,1,2,1]],"inputDisplay":"height = [0,1,0,2,1,0,1,3,2,1,2,1]"}::jsonb', '6::jsonb'),
  ('trapping-rain-water', 'sample', '{"input":[[4,2,0,3,2,5]],"inputDisplay":"height = [4,2,0,3,2,5]"}::jsonb', '9::jsonb'),
  ('trapping-rain-water', 'hidden', '{"input":[[2,0,2]]}::jsonb', '2::jsonb'),
  ('trapping-rain-water', 'hidden', '{"input":[[3,0,0,2,0,4]]}::jsonb', '10::jsonb'),
  ('trapping-rain-water', 'hidden', '{"input":[[0]]}::jsonb', '0::jsonb'),
  ('binary-search', 'sample', '{"input":[[-1,0,3,5,9,12],9],"inputDisplay":"nums = [-1,0,3,5,9,12], target = 9"}::jsonb', '4::jsonb'),
  ('binary-search', 'sample', '{"input":[[-1,0,3,5,9,12],2],"inputDisplay":"nums = [-1,0,3,5,9,12], target = 2"}::jsonb', '-1::jsonb'),
  ('binary-search', 'hidden', '{"input":[[5],5]}::jsonb', '0::jsonb'),
  ('binary-search', 'hidden', '{"input":[[2,5],5]}::jsonb', '1::jsonb'),
  ('binary-search', 'hidden', '{"input":[[2,5],2]}::jsonb', '0::jsonb'),
  ('binary-search', 'hidden', '{"input":[[1,3,5,7,9,11],8]}::jsonb', '-1::jsonb'),
  ('coin-change', 'sample', '{"input":[[1,2,5],11],"inputDisplay":"coins = [1,2,5], amount = 11"}::jsonb', '3::jsonb'),
  ('coin-change', 'sample', '{"input":[[2],3],"inputDisplay":"coins = [2], amount = 3"}::jsonb', '-1::jsonb'),
  ('coin-change', 'sample', '{"input":[[1],0],"inputDisplay":"coins = [1], amount = 0"}::jsonb', '0::jsonb'),
  ('coin-change', 'hidden', '{"input":[[186,419,83,408],6249]}::jsonb', '20::jsonb'),
  ('coin-change', 'hidden', '{"input":[[2,5,10,1],27]}::jsonb', '4::jsonb'),
  ('valid-anagram', 'sample', '{"input":["anagram","nagaram"],"inputDisplay":"s = \"anagram\", t = \"nagaram\""}::jsonb', 'true::jsonb'),
  ('valid-anagram', 'hidden', '{"input":["rat","car"]}::jsonb', 'false::jsonb'),
  ('reverse-linked-list', 'sample', '{"input":[[1,2,3,4,5]],"inputDisplay":"head = [1,2,3,4,5]"}::jsonb', '[5,4,3,2,1]::jsonb'),
  ('reverse-linked-list', 'hidden', '{"input":[[1,2]]}::jsonb', '[2,1]::jsonb'),
  ('binary-tree-inorder-traversal', 'sample', '{"input":[[1,null,2,3]],"inputDisplay":"root = [1,null,2,3]"}::jsonb', '[1,3,2]::jsonb'),
  ('binary-tree-inorder-traversal', 'hidden', '{"input":[[]]}::jsonb', '[]::jsonb'),
  ('maximum-depth-of-binary-tree', 'sample', '{"input":[[3,9,20,null,null,15,7]],"inputDisplay":"root = [3,9,20,null,null,15,7]"}::jsonb', '3::jsonb'),
  ('maximum-depth-of-binary-tree', 'hidden', '{"input":[[1,null,2]]}::jsonb', '2::jsonb'),
  ('intersection-of-two-arrays', 'sample', '{"input":[[1,2,2,1],[2,2]],"inputDisplay":"nums1 = [1,2,2,1], nums2 = [2,2]"}::jsonb', '[2]::jsonb'),
  ('intersection-of-two-arrays', 'hidden', '{"input":[[4,9,5],[9,4,9,8,4]]}::jsonb', '[9,4]::jsonb'),
  ('fibonacci-number', 'sample', '{"input":[4],"inputDisplay":"n = 4"}::jsonb', '3::jsonb'),
  ('fibonacci-number', 'hidden', '{"input":[10]}::jsonb', '55::jsonb'),
  ('single-number', 'sample', '{"input":[[2,2,1]],"inputDisplay":"nums = [2,2,1]"}::jsonb', '1::jsonb'),
  ('single-number', 'hidden', '{"input":[[4,1,2,1,2]]}::jsonb', '4::jsonb'),
  ('move-zeroes', 'sample', '{"input":[[0,1,0,3,12]],"inputDisplay":"nums = [0,1,0,3,12]"}::jsonb', '[1,3,12,0,0]::jsonb'),
  ('move-zeroes', 'hidden', '{"input":[[0]]}::jsonb', '[0]::jsonb'),
  ('plus-one', 'sample', '{"input":[[1,2,3]],"inputDisplay":"digits = [1,2,3]"}::jsonb', '[1,2,4]::jsonb'),
  ('plus-one', 'hidden', '{"input":[[9]]}::jsonb', '[1,0]::jsonb'),
  ('contains-duplicate', 'sample', '{"input":[[1,2,3,1]],"inputDisplay":"nums = [1,2,3,1]"}::jsonb', 'true::jsonb'),
  ('contains-duplicate', 'hidden', '{"input":[[1,2,3,4]]}::jsonb', 'false::jsonb');

-- Sanity checks
select problem_id, kind, count(*) from public.problem_tests group by 1, 2 order by 1, 2;
